version: '3.8'

networks:
  frontend-network:
    driver: bridge
  user-service-network:
    driver: bridge
  task-service-network:
    driver: bridge

volumes:
  roomietasks-userdb-data:
  roomietasks-taskdb-data:

services:
  # Frontend Service
  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    networks:
      - frontend-network
    depends_on:
      - user-service
      - task-service
    environment:
      - NODE_ENV=production

  # User Service
  user-service:
    build:
      context: ./Backend-User
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - frontend-network
      - user-service-network
    depends_on:
      - userdb
    environment:
      - DB_HOST=userdb
      - DB_DATABASE=userdb
      - DB_USER=root
      - DB_PASSWORD=rootpassword
      - JWT_SECRET=your_jwt_secret_key
      - JWT_EXPIRES_IN=24h

  # Task Service
  task-service:
    build:
      context: ./Backend-Task
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    networks:
      - frontend-network
      - task-service-network
    depends_on:
      - taskdb
      - user-service
    environment:
      - DB_HOST=taskdb
      - DB_DATABASE=taskdb
      - DB_USER=root
      - DB_PASSWORD=rootpassword
      - JWT_SECRET=your_jwt_secret_key
      - USER_SERVICE_URL=http://user-service:3000

  # User Database
  userdb:
    image: mysql:8.0
    networks:
      - user-service-network
    volumes:
      - roomietasks-userdb-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=userdb
    command: --default-authentication-plugin=mysql_native_password

  # Task Database
  taskdb:
    image: mysql:8.0
    networks:
      - task-service-network
    volumes:
      - roomietasks-taskdb-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=taskdb
    command: --default-authentication-plugin=mysql_native_password